branches:
  only:
  - master
sudo: false
language: python
cache:
  directories:
  - "$HOME/.cache/pip"
matrix:
  include:
  - python: pypy
  - python: '2.7'
install:
- pip install -U pip setuptools wheel
- pip install epsilon pytz pycrypto 'cryptography < 1.0'
- pip install .
script:
- "$(type -p trial) entropy"
notifications:
  email: false
  slack:
    secure: lqGRJQkQSBw9zX/AXqaPXVShw00TNncVvMAAj6q7jsLn17aCPmL5N0wmKWO6Oibdmu2EuehosCCN5JQ00tQ2zfi9sCGFtA5AC7Uxl2bi9rgBaW/HWSTc2q0ghi4v0MMCuxadOWOgjhRMKYNg37tIAuUYvJeB3kG8NFZgHKsxg0I=
